-- ============================================================
-- Medaea EHR — Schema Migration 002: Patient Registry
-- Version: 1.0.0 | Date: 2026-04-03 | Phase: 1
-- Tables: patients
-- ============================================================
-- ONC/CMS requirements met:
--   • Race, ethnicity, preferred_language (USCDI v3 Demographics)
--   • MRN — unique medical record number per organization
--   • SSN last 4 — for patient matching (never full SSN)
-- ============================================================

CREATE TABLE IF NOT EXISTS patients (
    id                  VARCHAR     PRIMARY KEY,                -- UUID v4
    first_name          VARCHAR     NOT NULL,
    last_name           VARCHAR     NOT NULL,
    email               VARCHAR,
    phone               VARCHAR(20),
    date_of_birth       VARCHAR(10),                           -- ISO date YYYY-MM-DD
    gender              VARCHAR(20),                           -- Male | Female | Other | Prefer not to say
    address             TEXT,
    city                VARCHAR,
    state               VARCHAR(2),
    zip                 VARCHAR(10),

    -- ONC USCDI v3 Required Demographics
    race                VARCHAR(100),                          -- OMB race categories
    ethnicity           VARCHAR(100),                          -- Hispanic/Latino or Not Hispanic/Latino
    preferred_language  VARCHAR(50),                          -- ISO 639-1 language code or name
    marital_status      VARCHAR(30),                          -- Single | Married | Divorced | Widowed | Separated

    -- Clinical identifiers
    ssn_last4           VARCHAR(4),                           -- Last 4 digits of SSN for patient matching
    mrn                 VARCHAR(50),                          -- Medical Record Number (org-unique)

    -- Status
    status              VARCHAR(20) NOT NULL DEFAULT 'active',
                                                              -- active | inactive | deceased

    -- Foreign keys
    organization_id     VARCHAR     REFERENCES organizations(id),
    primary_provider_id VARCHAR     REFERENCES users(id),

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_patients_org_id ON patients (organization_id);
CREATE INDEX IF NOT EXISTS idx_patients_mrn ON patients (mrn) WHERE mrn IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_patients_name ON patients (last_name, first_name);

COMMENT ON TABLE patients IS 'Patient registry. Central entity for all clinical data. Scoped to organization.';
COMMENT ON COLUMN patients.mrn IS 'Medical Record Number — unique per organization. Generated by registration workflow.';
COMMENT ON COLUMN patients.race IS 'ONC USCDI v3 requirement. OMB categories: American Indian/Alaska Native, Asian, Black/African American, Native Hawaiian/Pacific Islander, White, Other.';
COMMENT ON COLUMN patients.ethnicity IS 'ONC USCDI v3 requirement. OMB: Hispanic or Latino, Not Hispanic or Latino.';
COMMENT ON COLUMN patients.preferred_language IS 'ONC USCDI v3 requirement. Used for language concordance and interpreter services.';
COMMENT ON COLUMN patients.ssn_last4 IS 'HIPAA minimum necessary — only last 4 digits stored for patient matching. Never store full SSN.';
